-- Reglib/ITA/definitions/Core.lean
-- Core regulatory types for ITA_1961
-- Auto-generated by generate_reglib.py
-- Sources: rules JSONL + definitions JSONL (Reg 2 statutory definitions)
-- DO NOT EDIT MANUALLY — re-run the generator after updating either JSONL

namespace Reglib.ITA

/-! ## Primitive Type Aliases -/

/-- Indian Rupee amount in crore (1 crore = 10 million) -/
abbrev INR_Crore := Nat

/-- Percentage value as integer (0–100) -/
abbrev Pct := Nat

/-- Duration in months -/
abbrev Months := Nat

/-- Duration in years -/
abbrev Years := Nat

/-! ## Taxpayer -/

/-- Primary entity struct for ITA_1961 compliance checks -/
structure Taxpayer where
  /-- Reg 234B (maps_to inference) -/
  advance_tax_paid_amount                          : Nat
  /-- Reg 234B (maps_to inference) -/
  advance_tax_threshold_pct                        : Nat
  /-- Reg 234B (maps_to inference) -/
  assessed_tax_amount                              : Nat
  /-- Reg 139(1) (maps_to inference) -/
  basic_exemption_limit                            : Nat
  /-- Reg 139(1)(senior) (maps_to inference) -/
  basic_exemption_limit_senior                     : Nat
  /-- Reg 139(1)(senior) (maps_to inference) -/
  basic_exemption_limit_super_senior               : Nat
  /-- Reg 6(1) (maps_to inference) -/
  days_in_india_fy                                 : Nat
  /-- Reg 194(1) (maps_to inference) -/
  dividend_income_amount                           : Nat
  /-- Reg 80D(1) (maps_to inference) -/
  health_insurance_premium_amount                  : Nat
  /-- Reg 112A(holding) (maps_to inference) -/
  holding_period_months_equity                     : Months
  /-- Reg 194A(1)(bank) (maps_to inference) -/
  interest_income_bank_amount                      : Nat
  /-- Reg 194A(1)(bank) (maps_to inference) -/
  interest_threshold_bank                          : INR_Crore
  /-- Reg 194A(senior) (maps_to inference) -/
  interest_threshold_senior_bank                   : INR_Crore
  /-- Reg 80C(1) (maps_to inference) -/
  investment_80c_amount                            : Nat
  /-- Reg 87A(new) (maps_to inference) -/
  is_new_tax_regime                                : Bool
  /-- Reg 194(PAN) (maps_to inference) -/
  is_pan_furnished                                 : Bool
  /-- Reg 6(1)(check) (maps_to inference) -/
  is_resident                                      : Bool
  /-- Reg 139(1) (maps_to inference) -/
  is_return_filing_required                        : Bool
  /-- Reg 194A(senior) (maps_to inference) -/
  is_senior_citizen                                : Bool
  /-- Reg 112A(stt-acq) (maps_to inference) -/
  is_stt_paid_at_acquisition                       : Bool
  /-- Reg 111A(1) (maps_to inference) -/
  is_stt_paid_on_transfer                          : Bool
  /-- Reg 112A(1) (maps_to inference) -/
  ltcg_exempt_limit                                : Nat
  /-- Reg 112A(1) (maps_to inference) -/
  ltcg_listed_equity_amount                        : Nat
  /-- Reg 112A(1) (maps_to inference) -/
  ltcg_tax_rate_pct_x10                            : Nat
  /-- Reg 80C(1) (maps_to inference) -/
  max_80c_deduction                                : Nat
  /-- Reg 80D(1) (maps_to inference) -/
  max_80d_deduction_self                           : Nat
  /-- Reg 80D(senior) (maps_to inference) -/
  max_80d_deduction_senior                         : Nat
  /-- Reg 87A (maps_to inference) -/
  max_rebate_87a                                   : Nat
  /-- Reg 87A(new) (maps_to inference) -/
  max_rebate_87a_new                               : Nat
  /-- Reg 87A(new) (maps_to inference) -/
  rebate_87a_new_threshold                         : INR_Crore
  /-- Reg 87A (maps_to inference) -/
  rebate_87a_threshold                             : INR_Crore
  /-- Reg 111A(1) (maps_to inference) -/
  stcg_listed_equity_amount                        : Nat
  /-- Reg 111A(1) (maps_to inference) -/
  stcg_tax_rate_pct                                : Nat
  /-- Reg 194(1) (maps_to inference) -/
  tds_rate_194_dividend_pct                        : Nat
  /-- Reg 194A(1)(bank) (maps_to inference) -/
  tds_rate_194a_pct                                : Nat
  /-- Reg 194(PAN) (maps_to inference) -/
  tds_rate_no_pan_pct                              : Nat
  /-- Reg 87A (maps_to inference) -/
  total_income_amount                              : Nat
deriving Repr

end Reglib.ITA