-- Reglib.lean
-- Root import -- auto-generated by generate_reglib.py

import Reglib.ITA.definitions.Core
import Reglib.ITA.rules.Chapter1_Part1
import Reglib.ITA.rules.Chapter8_Part1
import Reglib.ITA.rules.Chapter12_Part1
import Reglib.ITA.rules.Chapter12_Part2
import Reglib.ITA.rules.ChapterVI_A_Part1
import Reglib.ITA.rules.ChapterXIV_Part1
import Reglib.ITA.rules.ChapterXVII_Part1
import Reglib.ITA.rules.ChapterVI_A_Part2
import Reglib.ITA.rules.ChapterXVII_Part2
import Reglib.ITA.rules.Compliance
