-- Reglib/ICDR/definitions/Core.lean
-- Core regulatory types for SEBI_ICDR_2018
-- Auto-generated by generate_reglib.py
-- Sources: rules JSONL + definitions JSONL (Reg 2 statutory definitions)
-- DO NOT EDIT MANUALLY — re-run the generator after updating either JSONL

namespace Reglib.ICDR

/-! ## Primitive Type Aliases -/

/-- Indian Rupee amount in crore (1 crore = 10 million) -/
abbrev INR_Crore := Nat

/-- Percentage value as integer (0–100) -/
abbrev Pct := Nat

/-- Duration in months -/
abbrev Months := Nat

/-- Duration in years -/
abbrev Years := Nat

/-! ## Inductive Types — grounded in Reg 2 statutory definitions -/

/-- Reg 2(eee), 2(eeea): specified securities -/
inductive SpecifiedSecurities where
  | equityShares          -- Reg 2(eee)
  | convertibleSecurities -- Reg 2(eee)
  | srEquityShares        -- Reg 2(eeea): superior voting rights
deriving Repr, DecidableEq

/-- Combined issue type — Reg 2(w),(q),(h),(xx),(nn),(tt) -/
inductive IssueType where
  | initialPublicOffer  -- Reg 2(w)
  | furtherPublicOffer  -- Reg 2(q)
  | compositeIssue      -- Reg 2(h): public-cum-rights simultaneously
  | rightsIssue         -- Reg 2(xx)
  | preferentialIssue   -- Reg 2(nn)
  | qualifiedPlacement  -- Reg 2(tt)
deriving Repr, DecidableEq

/-- Reg 2(k): convertible security -/
inductive ConvertibleSecurity where
  | convertibleIntoEquityShares
  | convertibleDebtInstrument
  | convertiblePreferenceShares
deriving Repr, DecidableEq

/-- Reg 2(ss): qualified institutional buyer -/
inductive QualifiedInstitutionalBuyer where
  | mutualFund
  | ventureCapitalFund
  | alternativeInvestmentFund
  | foreignVentureCapitalInvestor
  | publicFinancialInstitution
  | scheduledCommercialBank
  | multilateralAndBilateralDevelopmentFinancialInstitution
  | stateIndustrialDevelopmentCorporation
  | insuranceCompany
  | providentFund
  | pensionFund
  | nationalInvestmentFund
  | militaryInsuranceFunds
  | departmentOfPostsInsuranceFunds
deriving Repr, DecidableEq

/-- Reg 2(v): infrastructure sector -/
inductive InfrastructureSector where
  | transportation
  | agriculture
deriving Repr, DecidableEq

/-! ## Promoter — Reg 2(oo) -/

/-- A person included as promoter under any limb of Reg 2(oo)(i–iii) -/
structure Promoter where
  /-- Reg 2(oo)(i): named in offer doc or annual return (s.92 Companies Act) -/
  named_in_offer_doc                : Bool
  /-- Reg 2(oo)(ii): control as shareholder/director/otherwise -/
  has_control                       : Bool
  /-- Reg 2(oo)(iii): board accustomed to act on their advice -/
  board_acts_on_instructions        : Bool
  /-- Reg 2(oo) proviso: professional capacity only → excluded from promoter status -/
  acting_only_professionally        : Bool
  holding_pct                       : Pct
  is_debarred                       : Bool
  /-- Reg 2(lll) -/
  is_wilful_defaulter_or_fraudulent : Bool
  /-- Reg 2(p) -/
  is_fugitive_economic_offender     : Bool
deriving Repr

/-! ## Issuer — Reg 2(aa) -/

/-- "a company or a body corporate authorized to issue specified securities" -/
structure Issuer where
  /-- Reg 14(1)(proviso) (maps_to inference) -/
  alternative_contributor_max_pct                  : Nat
  /-- Reg 10(1)(d)(ii) (maps_to inference) -/
  assets_free_from_encumbrance                     : Bool
  /-- Reg 10(1)(d)(i) (maps_to inference) -/
  assets_sufficient_for_principal                  : Bool
  /-- Reg 16(1)(a)(proviso) (maps_to inference) -/
  capex_lockin_years                               : Years
  /-- Reg 8(proviso) (maps_to inference) -/
  combined_convertible_holding_period_months       : Months
  /-- Reg 8(explanation) (maps_to inference) -/
  conversion_completed_before_offer_doc            : Bool
  /-- Reg 11(2) (maps_to inference) -/
  convertible_debt_exceeds_ten_crore               : Bool
  /-- Reg 15(2) (maps_to inference) -/
  eligible_via_court_approved_scheme               : Bool
  /-- Reg 16(1)(b)(proviso) (maps_to inference) -/
  excess_holding_capex_lockin_years                : Years
  /-- Reg 16(1)(b) (maps_to inference) -/
  excess_holding_lockin_months                     : Months
  /-- Reg 7(1)(e) (maps_to inference) -/
  firm_finance_arrangement_pct                     : Nat
  /-- Reg 12(proviso) (maps_to inference) -/
  fully_convertible_debt_period_months             : Months
  /-- Reg 7(2) (maps_to inference) -/
  gcp_pct_limit                                    : Nat
  /-- Reg 7(3) (maps_to inference) -/
  gcp_unidentified_objects_pct_limit               : Nat
  /-- Reg 10(1)(d)(iii) (maps_to inference) -/
  has_consent_for_second_charge                    : Bool
  /-- Reg 10(1)(a) (maps_to inference) -/
  has_credit_rating                                : Bool
  /-- Reg 10(1)(b) (maps_to inference) -/
  has_debenture_trustee                            : Bool
  /-- Reg 7(1)(b) (maps_to inference) -/
  has_depository_agreement                         : Bool
  /-- Reg 5(1)(b) (maps_to inference) -/
  has_director_of_debarred_company                 : Bool
  /-- Reg 7(explanation)(II)(b)(ii) (maps_to inference) -/
  has_followed_accounting_standards                : Bool
  /-- Reg 5(1)(d) (maps_to inference) -/
  has_fugitive_economic_offender                   : Bool
  /-- Reg 14(1)(proviso)(2) (maps_to inference) -/
  has_identifiable_promoter                        : Bool
  /-- Reg 6(3) (maps_to inference) -/
  has_issued_sr_equity_shares                      : Bool
  /-- Reg 23(5) (maps_to inference) -/
  has_lead_manager_agreement                       : Bool
  /-- Reg 23(3) (maps_to inference) -/
  has_non_associate_lead_manager                   : Bool
  /-- Reg 6(3)(viii) (maps_to inference) -/
  has_only_one_sr_equity_class                     : Bool
  /-- Reg 5(2) (maps_to inference) -/
  has_outstanding_convertible_securities           : Bool
  /-- Reg 11(1) (maps_to inference) -/
  has_positive_consent_for_conversion              : Bool
  /-- Reg 23(1) (maps_to inference) -/
  has_registered_lead_manager                      : Bool
  /-- Reg 6(3)(iv) (maps_to inference) -/
  has_special_resolution_for_sr_shares             : Bool
  /-- Reg 4 (maps_to inference) -/
  is_conditions_satisfied_filing_date              : Bool
  /-- Reg 5(1)(explanation) (maps_to inference) -/
  is_debarment_period_over                         : Bool
  /-- Reg 5(1)(a) (maps_to inference) -/
  is_debarred                                      : Bool
  /-- Reg 6(1)(a)(proviso) (maps_to inference) -/
  is_excess_monetary_assets_utilised               : Bool
  /-- Reg 6(1)(a)(proviso)(2) (maps_to inference) -/
  is_ipo_entirely_ofs                              : Bool
  /-- Reg 6(3)(i) (maps_to inference) -/
  is_technology_intensive                          : Bool
  /-- Reg 5(1)(c) (maps_to inference) -/
  is_wilful_defaulter_or_fraudulent_borrower       : Bool
  /-- Reg 20 (maps_to inference) -/
  lockin_recorded_by_depository                    : Bool
  /-- Reg 8A(c) (maps_to inference) -/
  major_shareholder_lockin_applicable              : Bool
  /-- Reg 8A(a) (maps_to inference) -/
  major_shareholder_ofs_pct_limit                  : Nat
  /-- Reg 16(1)(a) (maps_to inference) -/
  min_contribution_lockin_months                   : Months
  /-- Reg 8A(b) (maps_to inference) -/
  minority_shareholder_ofs_pct_limit               : Nat
  /-- Reg 6(1)(a) (maps_to inference) -/
  net_tangible_assets_3yr                          : List INR_Crore
  /-- Reg 6(1)(c) (maps_to inference) -/
  net_worth_3yr                                    : List INR_Crore
  /-- Reg 12 (maps_to inference) -/
  no_cdi_for_promoter_group_financing              : Bool
  /-- Reg 9(proviso) (maps_to inference) -/
  no_debt_default_more_than_six_months             : Bool
  /-- Reg 17 (maps_to inference) -/
  non_promoter_lockin_months                       : Months
  /-- Reg 8 (maps_to inference) -/
  ofs_holding_period_years                         : Years
  /-- Reg 6(1)(b) (maps_to inference) -/
  operating_profit_avg_crore                       : List INR_Crore
  /-- Reg 19 (maps_to inference) -/
  partly_paid_lockin_years                         : Years
  /-- Reg 7(1)(d) (maps_to inference) -/
  partly_paid_shares_forfeited_or_paid             : Bool
  /-- Reg 15(1)(d) (maps_to inference) -/
  pledged_securities_ineligible                    : Bool
  /-- Reg 15(1)(b) (maps_to inference) -/
  price_comparison_applies                         : Bool
  /-- Reg 14(2)(b) (maps_to inference) -/
  promoter_contribution_not_below_weighted_avg     : Bool
  /-- Reg 14(2)(a) (maps_to inference) -/
  promoter_contribution_pct                        : Nat
  /-- Reg 14(2)(c) (maps_to inference) -/
  promoter_contribution_pct_issue_size             : Nat
  /-- Reg 14(2)(c) (maps_to inference) -/
  promoter_contribution_pct_project_cost           : Nat
  /-- Reg 14(4)(proviso)(2) (maps_to inference) -/
  promoter_initial_contribution_crore              : INR_Crore
  /-- Reg 21 (maps_to inference) -/
  promoter_lockin_pledgeable                       : Bool
  /-- Reg 14(1) (maps_to inference) -/
  promoter_min_holding_pct                         : Nat
  /-- Reg 7(1)(c) (maps_to inference) -/
  promoter_shares_dematerialised                   : Bool
  /-- Reg 6(2) (maps_to inference) -/
  qib_allotment_pct                                : Nat
  /-- Reg 10(2) (maps_to inference) -/
  redeems_per_offer_doc                            : Bool
  /-- Reg 11(3) (maps_to inference) -/
  redeems_unconverted_within_one_month             : Bool
  /-- Reg 6(1)(d) (maps_to inference) -/
  revenue_from_new_activity_pct                    : Nat
  /-- Reg 6(3)(iv)(c) (maps_to inference) -/
  sr_differential_dividends_disclosed              : Bool
  /-- Reg 6(3)(iv)(e) (maps_to inference) -/
  sr_equal_voting_matters_disclosed                : Bool
  /-- Reg 6(3)(iv)(a) (maps_to inference) -/
  sr_issue_size_disclosed                          : Bool
  /-- Reg 6(3)(ii) (maps_to inference) -/
  sr_shareholder_net_worth_max_crore               : Nat
  /-- Reg 6(3)(ix) (maps_to inference) -/
  sr_shares_equivalent_except_voting               : Bool
  /-- Reg 6(3)(v) (maps_to inference) -/
  sr_shares_holding_period_months                  : Months
  /-- Reg 6(3)(iii) (maps_to inference) -/
  sr_shares_issued_to_executive_promoters_only     : Bool
  /-- Reg 16(2) (maps_to inference) -/
  sr_shares_lockin_until_conversion                : Bool
  /-- Reg 6(3)(vii) (maps_to inference) -/
  sr_shares_same_face_value                        : Bool
  /-- Reg 6(3)(iv)(d) (maps_to inference) -/
  sr_sunset_provisions_disclosed                   : Bool
  /-- Reg 6(3)(iv)(b) (maps_to inference) -/
  sr_voting_ratio_disclosed                        : Bool
  /-- Reg 6(3)(vi) (maps_to inference) -/
  sr_voting_ratio_max                              : Nat
  /-- Reg 6(3)(vi) (maps_to inference) -/
  sr_voting_ratio_min                              : Nat
  /-- Reg 7(3)(proviso) (maps_to inference) -/
  unidentified_objects_pct_limit                   : Nat
  /-- Reg 17(c)(proviso) (maps_to inference) -/
  vcf_aif_lockin_months                            : Months
  /-- Reg 13(d) (maps_to inference) -/
  warrant_exercise_period_months                   : Months
  /-- Reg 13(a) (maps_to inference) -/
  warrant_tenure_months                            : Months
  /-- Reg 13(c) (maps_to inference) -/
  warrant_upfront_consideration_pct                : Nat
  /-- What kind of issue this filing is for -/
  issue_type                                         : IssueType
  /-- Type of securities being issued — Reg 2(eee) -/
  specified_securities_type                          : SpecifiedSecurities
  /-- Reg 2(oo) -/
  promoters                                          : List Promoter
deriving Repr

end Reglib.ICDR