-- Reglib/ITA/TaxProbe.lean
-- Auto-generated by generate_gold_probe.py — DO NOT EDIT MANUALLY
--
-- Contains one sorry theorem per gold-standard rule with real predicates.
-- The APOLLO verify_one.py loop fills in the proofs automatically.

import Reglib.ITA.rules.Compliance
import Reglib.ITA.rules.Chapter1_Part1
import Reglib.ITA.rules.Chapter8_Part1
import Reglib.ITA.rules.Chapter12_Part1
import Reglib.ITA.rules.Chapter12_Part2
import Reglib.ITA.rules.ChapterVI_A_Part1
import Reglib.ITA.rules.ChapterVI_A_Part2
import Reglib.ITA.rules.ChapterXIV_Part1
import Reglib.ITA.rules.ChapterXVII_Part1
import Reglib.ITA.rules.ChapterXVII_Part2

namespace Reglib.ITA.Rules

open Reglib.ITA

/-! ## Individual Sub-Clause Theorems -/

/-! ### Regulation 6 -/

/-- An individual is said to be resident in India in any previous year, if he has been in India during t... -/
theorem gold_ita_6_1 : reg_6_1 sample_taxpayer := by
  sorry

/-- Derived rule: an individual is resident if days_in_india_fy is at least 182. -/
theorem gold_ita_6_1_resident_check : reg_6_1_resident_check sample_taxpayer := by
  sorry

/-! ### Regulation 80c -/

/-- In computing the total income of an assessee, being an individual or a Hindu undivided family, there... -/
theorem gold_ita_80c_1 : reg_80c_1 sample_taxpayer := by
  sorry

/-! ### Regulation 80d -/

/-- In computing the total income of an assessee, being an individual or a Hindu undivided family, there... -/
theorem gold_ita_80d_1 : reg_80d_1 sample_taxpayer := by
  sorry

/-- In case of a senior citizen, the deduction limit under section 80D for health insurance premium shal... -/
theorem gold_ita_80d_senior : reg_80d_senior sample_taxpayer := by
  sorry

/-! ### Regulation 87a -/

/-- An assessee, being an individual resident in India, whose total income does not exceed five hundred ... -/
theorem gold_ita_87a_rebate : reg_87a_rebate sample_taxpayer := by
  sorry

/-- Under the new tax regime (section 115BAC), the rebate under section 87A is available up to twenty-fi... -/
theorem gold_ita_87a_new_regime : reg_87a_new_regime sample_taxpayer := by
  sorry

/-! ### Regulation 111a -/

/-- Where the total income of an assessee includes any income chargeable under the head capital gains, a... -/
theorem gold_ita_111a_1 : reg_111a_1 sample_taxpayer := by
  sorry

/-- Derived eligibility: section 111A applies only if STT was paid on the transfer of the listed equity ... -/
theorem gold_ita_111a_stt_check : reg_111a_stt_check sample_taxpayer := by
  sorry

/-! ### Regulation 112a -/

/-- Where the total income of an assessee includes any income chargeable under the head capital gains, a... -/
theorem gold_ita_112a_1 : reg_112a_1 sample_taxpayer := by
  sorry

/-- Derived rule: an equity share in a listed company is a long-term capital asset if held for more than... -/
theorem gold_ita_112a_holding : reg_112a_holding sample_taxpayer := by
  sorry

/-- Derived eligibility: section 112A applies only if STT was paid both at acquisition and at transfer o... -/
theorem gold_ita_112a_stt_acquisition : reg_112a_stt_acquisition sample_taxpayer := by
  sorry

/-- The amount of long-term capital gains of one lakh twenty-five thousand rupees shall not be chargeabl... -/
theorem gold_ita_112a_exemption : reg_112a_exemption sample_taxpayer := by
  sorry

/-! ### Regulation 139 -/

/-- Every person, being an individual whose total income of the previous year exceeds the maximum amount... -/
theorem gold_ita_139_1_filing : reg_139_1_filing sample_taxpayer := by
  sorry

/-- For a senior citizen (age 60 to 80 years), the basic exemption limit is three lakh rupees. For a sup... -/
theorem gold_ita_139_senior_exemption : reg_139_senior_exemption sample_taxpayer := by
  sorry

/-! ### Regulation 194 -/

/-- Any person responsible for paying to a resident any income by way of dividends shall, at the time of... -/
theorem gold_ita_194_1 : reg_194_1 sample_taxpayer := by
  sorry

/-- Where the recipient does not furnish PAN to the payer, TDS shall be deducted at the higher of the ra... -/
theorem gold_ita_194_pan_check : reg_194_pan_check sample_taxpayer := by
  sorry

/-! ### Regulation 194a -/

/-- Any person, not being an individual or a Hindu undivided family, responsible for paying to a residen... -/
theorem gold_ita_194a_1_bank : reg_194a_1_bank sample_taxpayer := by
  sorry

/-- The threshold for TDS on interest from banking companies is fifty thousand rupees for a senior citiz... -/
theorem gold_ita_194a_senior_citizen : reg_194a_senior_citizen sample_taxpayer := by
  sorry

/-! ### Regulation 234b -/

/-- Where, in any financial year, an assessee who is liable to pay advance tax has failed to pay such ta... -/
theorem gold_ita_234b_advance_tax : reg_234b_advance_tax sample_taxpayer := by
  sorry

/-! ## Composite Gate Theorems -/
--
-- These prove reg_N_eligible (the conjunction of all sub-clauses).
-- APOLLO decomposition: prove each sub-clause first, then combine.

/-- Composite gate: reg_6_eligible = reg_6_1, reg_6_1_resident_check -/
theorem gold_reg_6_eligible : reg_6_eligible sample_taxpayer := by
  sorry

/-- Composite gate: reg_139_eligible = reg_139_1_filing, reg_139_senior_exemption -/
theorem gold_reg_139_eligible : reg_139_eligible sample_taxpayer := by
  sorry

/-- Composite gate: reg_194_eligible = reg_194_1, reg_194_pan_check -/
theorem gold_reg_194_eligible : reg_194_eligible sample_taxpayer := by
  sorry

/-- Composite gate: reg_111a_eligible = reg_111a_1, reg_111a_stt_check -/
theorem gold_reg_111a_eligible : reg_111a_eligible sample_taxpayer := by
  sorry

/-- Composite gate: reg_112a_eligible = reg_112a_1, reg_112a_holding, reg_112a_stt_acquisition, reg_112a_exemption -/
theorem gold_reg_112a_eligible : reg_112a_eligible sample_taxpayer := by
  sorry

/-- Composite gate: reg_194a_eligible = reg_194a_1_bank, reg_194a_senior_citizen -/
theorem gold_reg_194a_eligible : reg_194a_eligible sample_taxpayer := by
  sorry

/-- Composite gate: reg_80d_eligible = reg_80d_1, reg_80d_senior -/
theorem gold_reg_80d_eligible : reg_80d_eligible sample_taxpayer := by
  sorry

/-- Composite gate: reg_87a_eligible = reg_87a_rebate, reg_87a_new_regime -/
theorem gold_reg_87a_eligible : reg_87a_eligible sample_taxpayer := by
  sorry

end Reglib.ITA.Rules
