#!/usr/bin/env python3
"""
generate_taxpayer_lean.py
=========================
Generates Reglib_tax/Reglib/ITA/instances/SampleTaxpayer.lean from
the extracted taxpayer_fields.json.

Usage:
    python scripts/generate_taxpayer_lean.py \
        --fields data/tax/taxpayer_fields.json \
        --out    Reglib_tax/Reglib/ITA/instances/SampleTaxpayer.lean
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


LEAN_HEADER = """\
-- Reglib_tax/Reglib/ITA/instances/SampleTaxpayer.lean
-- Auto-generated by generate_taxpayer_lean.py — DO NOT EDIT MANUALLY
-- Source: taxpayer_fields.json extracted from ITR-2 XML

import Reglib.ITA.definitions.Core

namespace Reglib.ITA

open Reglib.ITA

/-!
## Sample Taxpayer Instance

A concrete `Taxpayer` struct populated from a real ITR-2 filing.
All tax rule theorems in TaxProbe.lean are proved against this instance.
-/

def sample_taxpayer : Taxpayer := {
"""

LEAN_FOOTER = """\
}

end Reglib.ITA
"""


def python_to_lean(value) -> str:
    """Convert a Python value to a Lean 4 literal."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return str(int(value))
    if isinstance(value, str):
        return f'"{value}"'
    return str(value)


def generate_sample_taxpayer(fields: dict) -> str:
    lines = [LEAN_HEADER]
    for field, value in fields.items():
        lean_val = python_to_lean(value)
        lines.append(f"  {field} := {lean_val},")
    lines.append(LEAN_FOOTER)
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--fields", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    args = parser.parse_args()

    with open(args.fields, encoding="utf-8") as f:
        fields = json.load(f)

    content = generate_sample_taxpayer(fields)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(content, encoding="utf-8")
    print(f"[generate_taxpayer_lean] Written: {args.out}")


if __name__ == "__main__":
    main()
