#!/usr/bin/env python3
"""
generate_gold_probe.py
======================
Generates Reglib_gold/Reglib/ICDR/GoldProbe.lean from the gold-standard rules JSONL.

Inclusion rule:
  - Include a theorem for every rule where maps_to is non-empty.
  - Skip rules with empty maps_to (sorry stubs with no fields to prove).
  - Composite gates (generated by generate_reglib.py) also get theorems.

Output theorem format:
  theorem gold_reg_5_1_a : reg_5_1_a sample_compliant_issuer := by sorry

Usage:
    python scripts/generate_gold_probe.py \
        --rules data/gold_standard/gold_standard_regs_4_23.jsonl \
        --out   Reglib_gold/Reglib/ICDR/GoldProbe.lean
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path


def sanitize_def_name(rule_id: str) -> str:
    name = rule_id.lower().replace("icdr_", "reg_").replace("ita_", "reg_")
    return re.sub(r"[^a-z0-9_]", "_", name)


def _theorem_name(rule_id: str) -> str:
    if str(rule_id or "").upper().startswith("ITA_"):
        return "gold_" + str(rule_id).lower()
    return "gold_" + sanitize_def_name(rule_id)


def _top_reg(rule_id: str) -> str:
    """Top regulation token — must match generate_reglib._top_reg."""
    s = str(rule_id or "")
    m = re.match(r"ICDR_(\d+)", s, re.I)
    if m:
        return m.group(1)
    m = re.match(r"ITA_([0-9]+[a-z]?)", s, re.I)
    return m.group(1).lower() if m else ""


def _is_proviso_or_explanation(rule_id: str) -> bool:
    s = str(rule_id or "").lower()
    return ("proviso" in s) or ("explanation" in s)


ROMAN = {
    "I": 1, "II": 2, "III": 3, "IV": 4, "V": 5,
    "VI": 6, "VII": 7, "VIII": 8, "IX": 9, "X": 10,
    "XI": 11, "XII": 12,
}


def part_file_name(chapter_number: str, part_number: str) -> str:
    """Must match generate_reglib.part_file_name exactly."""
    ch = ROMAN.get(str(chapter_number), chapter_number)
    pt = ROMAN.get(str(part_number), part_number)
    ch_safe = re.sub(r"[^a-zA-Z0-9]", "_", str(ch))
    pt_safe = re.sub(r"[^a-zA-Z0-9]", "_", str(pt))
    return f"Chapter{ch_safe}_Part{pt_safe}"


def load_rules(path: Path) -> list[dict]:
    rules = []
    with open(path, encoding="utf-8") as f:
        for i, line in enumerate(f):
            line = line.strip()
            if not line:
                continue
            try:
                rules.append(json.loads(line))
            except json.JSONDecodeError as e:
                print(f"[WARN] line {i+1}: {e}", file=sys.stderr)
    return rules


def get_composite_gates(rules: list[dict]) -> list[dict]:
    """Synthetic composite gate entries matching generate_reglib.py reg_{N}_eligible."""
    reg_groups: dict[str, list[dict]] = defaultdict(list)
    for rule in rules:
        top = _top_reg(rule["rule_id"])
        if top:
            reg_groups[top].append(rule)

    composites = []
    for top_reg in sorted(reg_groups.keys(), key=lambda x: int(x) if x.isdigit() else 999):
        reg_rules = reg_groups[top_reg]
        real_sub_clauses = [
            r for r in reg_rules
            if r.get("maps_to") and not _is_proviso_or_explanation(r["rule_id"])
        ]
        if len(real_sub_clauses) > 1:
            gate_name = f"reg_{top_reg}_eligible"
            rep_rule = real_sub_clauses[0]
            composites.append({
                "rule_id": f"COMPOSITE_{top_reg}",
                "def_name": gate_name,
                "theorem_name": f"gold_{gate_name}",
                "text": rep_rule.get("text", "")[:80],
                "is_composite": True,
                "sub_clauses": [sanitize_def_name(r["rule_id"]) for r in real_sub_clauses],
                "maps_to": [m for r in real_sub_clauses for m in (r.get("maps_to") or [])],
            })
    return composites


def generate_gold_probe(
    rules: list[dict],
    subdir: str = "ICDR",
    instance_name: str = "sample_compliant_issuer",
    probe_stem: str = "GoldProbe",
) -> str:
    chapter_parts: set[tuple[str, str]] = set()
    for rule in rules:
        ch = (rule.get("chapter") or {}).get("number", "II")
        pt = (rule.get("part") or {}).get("number", "I")
        chapter_parts.add((ch, pt))

    import_names = sorted(
        {part_file_name(ch, pt) for ch, pt in chapter_parts},
        key=lambda s: [int(x) if x.isdigit() else x for x in re.split(r"(\d+)", s)],
    )

    lines = [
        f"-- Reglib/{subdir}/{probe_stem}.lean",
        "-- Auto-generated by generate_gold_probe.py — DO NOT EDIT MANUALLY",
        "--",
        "-- Contains one sorry theorem per gold-standard rule with real predicates.",
        "-- The APOLLO verify_one.py loop fills in the proofs automatically.",
        "",
        f"import Reglib.{subdir}.rules.Compliance",
    ]
    for imp in import_names:
        lines.append(f"import Reglib.{subdir}.rules.{imp}")

    lines += [
        "",
        f"namespace Reglib.{subdir}.Rules",
        "",
        f"open Reglib.{subdir}",
        "",
        "/-! ## Individual Sub-Clause Theorems -/",
        "",
    ]

    included = []
    skipped = []

    reg_groups: dict[str, list[dict]] = defaultdict(list)
    for rule in rules:
        top = _top_reg(rule["rule_id"]) or "0"
        reg_groups[top].append(rule)

    sorted_tops = sorted(
        reg_groups.keys(),
        key=lambda x: int(re.match(r"\d+", x).group()) if re.match(r"\d+", x) else 999,
    )

    for top_reg in sorted_tops:
        reg_rules = reg_groups[top_reg]
        lines.append(f"/-! ### Regulation {top_reg} -/")
        lines.append("")

        for rule in reg_rules:
            rule_id = rule["rule_id"]
            def_name = sanitize_def_name(rule_id)
            maps_to = rule.get("maps_to") or []
            text = rule.get("text", "").strip()[:100].replace("\n", " ").replace('"', "'")

            if not maps_to:
                skipped.append(rule_id)
                lines.append(f"-- SKIPPED {rule_id}: no maps_to fields extracted")
                lines.append("")
                continue

            thm_name = _theorem_name(rule_id)
            included.append(thm_name)
            lines.append(f"/-- {text}{'...' if len(rule.get('text', '')) > 100 else ''} -/")
            lines.append(f"theorem {thm_name} : {def_name} {instance_name} := by")
            lines.append("  sorry")
            lines.append("")

    composites = get_composite_gates(rules)
    if composites:
        lines += [
            "/-! ## Composite Gate Theorems -/",
            "--",
            "-- These prove reg_N_eligible (the conjunction of all sub-clauses).",
            "-- APOLLO decomposition: prove each sub-clause first, then combine.",
            "",
        ]
        for c in composites:
            thm_name = c["theorem_name"]
            def_name = c["def_name"]
            included.append(thm_name)
            sub_str = ", ".join(c["sub_clauses"])
            lines.append(f"/-- Composite gate: {def_name} = {sub_str} -/")
            lines.append(f"theorem {thm_name} : {def_name} {instance_name} := by")
            lines.append("  sorry")
            lines.append("")

    lines.append(f"end Reglib.{subdir}.Rules")
    lines.append("")

    print(f"[generate_gold_probe] Included: {len(included)} theorems", file=sys.stderr)
    print(f"[generate_gold_probe] Skipped:  {len(skipped)} rules (no maps_to)", file=sys.stderr)
    print(f"[generate_gold_probe] Composite gates: {len(composites)}", file=sys.stderr)

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate GoldProbe.lean from gold JSONL")
    parser.add_argument("--rules", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    parser.add_argument("--subdir", default="ICDR", help="Reglib subdir (ICDR or ITA)")
    parser.add_argument(
        "--instance-name",
        default="sample_compliant_issuer",
        help="Sample instance in Compliance.lean (sample_taxpayer for ITA)",
    )
    args = parser.parse_args()

    rules = load_rules(args.rules)
    probe_stem = args.out.stem
    content = generate_gold_probe(
        rules,
        subdir=args.subdir,
        instance_name=args.instance_name,
        probe_stem=probe_stem,
    )

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(content, encoding="utf-8")
    print(f"[generate_gold_probe] Written: {args.out}", file=sys.stderr)


if __name__ == "__main__":
    main()
