-- Reglib/ICDR/GoldProbe.lean
-- Auto-generated by generate_gold_probe.py — DO NOT EDIT MANUALLY
--
-- Contains one sorry theorem per gold-standard rule with real predicates.
-- The APOLLO verify_one.py loop fills in the proofs automatically.

import Reglib.ICDR.rules.Compliance
import Reglib.ICDR.rules.Chapter2_Part1
import Reglib.ICDR.rules.Chapter2_Part2
import Reglib.ICDR.rules.Chapter2_Part3
import Reglib.ICDR.rules.Chapter2_Part4
import Reglib.ICDR.rules.Chapter2_Part5

namespace Reglib.ICDR.Rules

open Reglib.ICDR

/-! ## Individual Sub-Clause Theorems -/

/-! ### Regulation 4 -/

/-- Unless otherwise provided in this Chapter, an issuer making an initial public offer of specified sec... -/
theorem gold_reg_4 : reg_4 sample_compliant_issuer := by
  sorry

/-! ### Regulation 5 -/

/-- if the issuer, any of its promoters, promoter group or directors or selling shareholders are debarre... -/
theorem gold_reg_5_1_a : reg_5_1_a sample_compliant_issuer := by
  sorry

/-- if any of the promoters or directors of the issuer is a promoter or director of any other company wh... -/
theorem gold_reg_5_1_b : reg_5_1_b sample_compliant_issuer := by
  sorry

/-- if the issuer or any of its promoters or directors is a [wilful defaulter or a fraudulent borrower.] -/
theorem gold_reg_5_1_c : reg_5_1_c sample_compliant_issuer := by
  sorry

/-- if any of its promoters or directors is a fugitive economic offender. -/
theorem gold_reg_5_1_d : reg_5_1_d sample_compliant_issuer := by
  sorry

/-- The restrictions under (a) and (b) above shall not apply to the persons or entities mentioned therei... -/
theorem gold_reg_5_1_explanation : reg_5_1_explanation sample_compliant_issuer := by
  sorry

/-- An issuer shall not be eligible to make an initial public offer if there are any outstanding convert... -/
theorem gold_reg_5_2 : reg_5_2 sample_compliant_issuer := by
  sorry

-- SKIPPED ICDR_5_2_proviso: no maps_to fields extracted

-- SKIPPED ICDR_5_2_proviso_2: no maps_to fields extracted

-- SKIPPED ICDR_5_2_proviso_3: no maps_to fields extracted

/-! ### Regulation 6 -/

/-- it has net tangible assets of at least three crore rupees, calculated on a restated and consolidated... -/
theorem gold_reg_6_1_a : reg_6_1_a sample_compliant_issuer := by
  sorry

/-- if more than fifty per cent. of the net tangible assets are held in monetary assets, the issuer has ... -/
theorem gold_reg_6_1_proviso : reg_6_1_proviso sample_compliant_issuer := by
  sorry

/-- the limit of fifty per cent. on monetary assets shall not be applicable in case the initial public o... -/
theorem gold_reg_6_1_proviso_2 : reg_6_1_proviso_2 sample_compliant_issuer := by
  sorry

/-- it has an average operating profit of at least fifteen crore rupees, calculated on a restated and co... -/
theorem gold_reg_6_1_b : reg_6_1_b sample_compliant_issuer := by
  sorry

/-- it has a net worth of at least one crore rupees in each of the preceding three full years (of twelve... -/
theorem gold_reg_6_1_c : reg_6_1_c sample_compliant_issuer := by
  sorry

/-- if it has changed its name within the last one year, at least fifty per cent. of the revenue, calcul... -/
theorem gold_reg_6_1_d : reg_6_1_d sample_compliant_issuer := by
  sorry

/-- An issuer not satisfying the condition stipulated in sub-regulation (1) shall be eligible to make an... -/
theorem gold_reg_6_2 : reg_6_2 sample_compliant_issuer := by
  sorry

/-- If an issuer has issued SR equity shares to its promoters/ founders, the said issuer shall be allowe... -/
theorem gold_reg_6_3 : reg_6_3 sample_compliant_issuer := by
  sorry

/-- the issuer shall be intensive in the use of technology, information technology, intellectual propert... -/
theorem gold_reg_6_3_i : reg_6_3_i sample_compliant_issuer := by
  sorry

/-- the net worth of the SR shareholder, as determined by a Registered Valuer, shall not be more than ru... -/
theorem gold_reg_6_3_ii : reg_6_3_ii sample_compliant_issuer := by
  sorry

-- SKIPPED ICDR_6_3_ii_explanation: no maps_to fields extracted

/-- The SR shares were issued only to the promoters/ founders who hold an executive position in the issu... -/
theorem gold_reg_6_3_iii : reg_6_3_iii sample_compliant_issuer := by
  sorry

/-- The issue of SR equity shares had been authorized by a special resolution passed at a general meetin... -/
theorem gold_reg_6_3_iv : reg_6_3_iv sample_compliant_issuer := by
  sorry

/-- the size of issue of SR equity shares, -/
theorem gold_reg_6_3_iv_a : reg_6_3_iv_a sample_compliant_issuer := by
  sorry

/-- ratio of voting rights of SR equity shares vis-à-vis the ordinary shares, -/
theorem gold_reg_6_3_iv_b : reg_6_3_iv_b sample_compliant_issuer := by
  sorry

/-- rights as to differential dividends, if any -/
theorem gold_reg_6_3_iv_c : reg_6_3_iv_c sample_compliant_issuer := by
  sorry

/-- sunset provisions, which provide for a time frame for the validity of such SR equity shares, -/
theorem gold_reg_6_3_iv_d : reg_6_3_iv_d sample_compliant_issuer := by
  sorry

/-- matters in respect of which the SR equity shares would have the same voting right as that of the ord... -/
theorem gold_reg_6_3_iv_e : reg_6_3_iv_e sample_compliant_issuer := by
  sorry

/-- the SR equity shares have been issued prior to the filing of draft red herring prospectus and held f... -/
theorem gold_reg_6_3_v : reg_6_3_v sample_compliant_issuer := by
  sorry

/-- The SR equity shares shall have voting rights in the ratio of a minimum of 2:1 upto a maximum of 10:... -/
theorem gold_reg_6_3_vi : reg_6_3_vi sample_compliant_issuer := by
  sorry

/-- The SR equity shares shall have the same face value as the ordinary shares; -/
theorem gold_reg_6_3_vii : reg_6_3_vii sample_compliant_issuer := by
  sorry

/-- The issuer shall only have one class of SR equity shares; -/
theorem gold_reg_6_3_viii : reg_6_3_viii sample_compliant_issuer := by
  sorry

/-- The SR equity shares shall be equivalent to ordinary equity shares in all respects, except for havin... -/
theorem gold_reg_6_3_ix : reg_6_3_ix sample_compliant_issuer := by
  sorry

/-! ### Regulation 7 -/

-- SKIPPED ICDR_7_1_a: no maps_to fields extracted

/-- it has entered into an agreement with a depository for dematerialisation of the specified securities... -/
theorem gold_reg_7_1_b : reg_7_1_b sample_compliant_issuer := by
  sorry

/-- all its specified securities held by the promoters are in dematerialised form prior to filing of the... -/
theorem gold_reg_7_1_c : reg_7_1_c sample_compliant_issuer := by
  sorry

/-- all its existing partly paid-up equity shares have either been fully paid-up or have been forfeited; -/
theorem gold_reg_7_1_d : reg_7_1_d sample_compliant_issuer := by
  sorry

/-- it has made firm arrangements of finance through verifiable means towards seventy five per cent. of ... -/
theorem gold_reg_7_1_e : reg_7_1_e sample_compliant_issuer := by
  sorry

/-- The amount for general corporate purposes, as mentioned in objects of the issue in the draft offer d... -/
theorem gold_reg_7_2 : reg_7_2 sample_compliant_issuer := by
  sorry

/-- The amount for: (i) general corporate purposes, and (ii) such objects where the issuer company has n... -/
theorem gold_reg_7_3 : reg_7_3 sample_compliant_issuer := by
  sorry

/-- the amount raised for such objects where the issuer company has not identified acquisition or invest... -/
theorem gold_reg_7_3_proviso : reg_7_3_proviso sample_compliant_issuer := by
  sorry

-- SKIPPED ICDR_7_3_proviso_2: no maps_to fields extracted

-- SKIPPED ICDR_7_explanation_b_i: no maps_to fields extracted

/-- the applicable accounting standards have been followed; -/
theorem gold_reg_7_explanation_b_ii : reg_7_explanation_b_ii sample_compliant_issuer := by
  sorry

-- SKIPPED ICDR_7_explanation_b_iii: no maps_to fields extracted

-- SKIPPED ICDR_7_explanation: no maps_to fields extracted

/-! ### Regulation 8 -/

/-- Only such fully paid-up equity shares may be offered for sale to the public, which have been held by... -/
theorem gold_reg_8 : reg_8 sample_compliant_issuer := by
  sorry

/-- in case the equity shares received on conversion or exchange of fully paid-up compulsorily convertib... -/
theorem gold_reg_8_proviso : reg_8_proviso sample_compliant_issuer := by
  sorry

-- SKIPPED ICDR_8_proviso_2: no maps_to fields extracted

/-- If the equity shares arising out of the conversion or exchange of the fully paid-up compulsorily con... -/
theorem gold_reg_8_explanation : reg_8_explanation sample_compliant_issuer := by
  sorry

-- SKIPPED ICDR_8_proviso_3: no maps_to fields extracted

-- SKIPPED ICDR_8_proviso_3_a: no maps_to fields extracted

-- SKIPPED ICDR_8_proviso_3_b: no maps_to fields extracted

-- SKIPPED ICDR_8_proviso_3_c: no maps_to fields extracted

-- SKIPPED ICDR_8_proviso_3_c_i: no maps_to fields extracted

-- SKIPPED ICDR_8_proviso_3_c_ii: no maps_to fields extracted

/-- shares offered for sale to the public by shareholder(s) holding, individually or with persons acting... -/
theorem gold_reg_8a_a : reg_8a_a sample_compliant_issuer := by
  sorry

/-- shares offered for sale to the public by shareholder(s) holding, individually or with persons acting... -/
theorem gold_reg_8a_b : reg_8a_b sample_compliant_issuer := by
  sorry

/-- for shareholder(s) holding, individually or with persons acting in concert, more than twenty per cen... -/
theorem gold_reg_8a_c : reg_8a_c sample_compliant_issuer := by
  sorry

-- SKIPPED ICDR_8a_explanation: no maps_to fields extracted

/-! ### Regulation 9 -/

-- SKIPPED ICDR_9: no maps_to fields extracted

/-- it is not in default of payment of interest or repayment of principal amount in respect of debt inst... -/
theorem gold_reg_9_proviso : reg_9_proviso sample_compliant_issuer := by
  sorry

/-! ### Regulation 10 -/

-- SKIPPED ICDR_10_1: no maps_to fields extracted

/-- it has obtained credit rating from at least one credit rating agency; -/
theorem gold_reg_10_1_a : reg_10_1_a sample_compliant_issuer := by
  sorry

/-- it has appointed at least one debenture trustee in accordance with the provisions of the Companies A... -/
theorem gold_reg_10_1_b : reg_10_1_b sample_compliant_issuer := by
  sorry

-- SKIPPED ICDR_10_1_c: no maps_to fields extracted

-- SKIPPED ICDR_10_1_d: no maps_to fields extracted

/-- such assets are sufficient to discharge the principal amount at all times; -/
theorem gold_reg_10_1_d_i : reg_10_1_d_i sample_compliant_issuer := by
  sorry

/-- such assets are free from any encumbrance; -/
theorem gold_reg_10_1_d_ii : reg_10_1_d_ii sample_compliant_issuer := by
  sorry

/-- where security is already created on such assets in favour of any existing lender or security truste... -/
theorem gold_reg_10_1_d_iii : reg_10_1_d_iii sample_compliant_issuer := by
  sorry

-- SKIPPED ICDR_10_1_d_iv: no maps_to fields extracted

/-- The issuer shall redeem the convertible debt instruments in terms of the offer document. -/
theorem gold_reg_10_2 : reg_10_2 sample_compliant_issuer := by
  sorry

/-! ### Regulation 11 -/

/-- The issuer shall not convert its optionally convertible debt instruments into equity shares unless t... -/
theorem gold_reg_11_1 : reg_11_1 sample_compliant_issuer := by
  sorry

/-- Where the value of the convertible portion of any listed convertible debt instruments issued by an i... -/
theorem gold_reg_11_2 : reg_11_2 sample_compliant_issuer := by
  sorry

-- SKIPPED ICDR_11_2_proviso: no maps_to fields extracted

/-- Where an option is to be given to the holders of the convertible debt instruments in terms of sub-re... -/
theorem gold_reg_11_3 : reg_11_3 sample_compliant_issuer := by
  sorry

-- SKIPPED ICDR_11_4: no maps_to fields extracted

/-! ### Regulation 12 -/

/-- An issuer shall not issue convertible debt instruments for financing or for providing loans to or fo... -/
theorem gold_reg_12 : reg_12 sample_compliant_issuer := by
  sorry

/-- an issuer shall be eligible to issue fully convertible debt instruments for these purposes if the pe... -/
theorem gold_reg_12_proviso : reg_12_proviso sample_compliant_issuer := by
  sorry

/-! ### Regulation 13 -/

/-- the tenure of such warrants shall not exceed eighteen months from the date of their allotment in the... -/
theorem gold_reg_13_a : reg_13_a sample_compliant_issuer := by
  sorry

-- SKIPPED ICDR_13_b: no maps_to fields extracted

/-- the price or formula for determination of exercise price of the warrants shall be determined upfront... -/
theorem gold_reg_13_c : reg_13_c sample_compliant_issuer := by
  sorry

-- SKIPPED ICDR_13_proviso: no maps_to fields extracted

/-- in case the warrant holder does not exercise the option to take equity shares against any of the war... -/
theorem gold_reg_13_d : reg_13_d sample_compliant_issuer := by
  sorry

/-! ### Regulation 14 -/

/-- The promoters of the issuer shall hold at least twenty per cent. of the post-issue capital: -/
theorem gold_reg_14_1 : reg_14_1 sample_compliant_issuer := by
  sorry

/-- in case the post-issue shareholding of the promoters is less than twenty per cent., alternative inve... -/
theorem gold_reg_14_proviso : reg_14_proviso sample_compliant_issuer := by
  sorry

/-- the requirement of minimum promoters' contribution shall not apply in case an issuer does not have a... -/
theorem gold_reg_14_proviso_2 : reg_14_proviso_2 sample_compliant_issuer := by
  sorry

-- SKIPPED ICDR_14_2: no maps_to fields extracted

/-- the promoters shall contribute twenty per cent. as stipulated in sub-regulation (1), as the case may... -/
theorem gold_reg_14_a : reg_14_a sample_compliant_issuer := by
  sorry

-- SKIPPED ICDR_14_a_proviso: no maps_to fields extracted

/-- in case of any issue of convertible securities which are convertible or exchangeable on different da... -/
theorem gold_reg_14_b : reg_14_b sample_compliant_issuer := by
  sorry

/-- subject to the provisions of clause (a) and (b) above, in case of an initial public offer of convert... -/
theorem gold_reg_14_c : reg_14_c sample_compliant_issuer := by
  sorry

-- SKIPPED ICDR_14_c_proviso: no maps_to fields extracted

-- SKIPPED ICDR_14_3: no maps_to fields extracted

-- SKIPPED ICDR_14_4: no maps_to fields extracted

-- SKIPPED ICDR_14_4_proviso: no maps_to fields extracted

/-- where the minimum promoters' contribution is more than one hundred crore rupees and the initial publ... -/
theorem gold_reg_14_4_proviso_2 : reg_14_4_proviso_2 sample_compliant_issuer := by
  sorry

/-! ### Regulation 15 -/

-- SKIPPED ICDR_15_1_a: no maps_to fields extracted

-- SKIPPED ICDR_15_1_a_i: no maps_to fields extracted

-- SKIPPED ICDR_15_1_a_ii: no maps_to fields extracted

/-- specified securities acquired by the promoters and alternative investment funds or foreign venture c... -/
theorem gold_reg_15_1_b : reg_15_1_b sample_compliant_issuer := by
  sorry

-- SKIPPED ICDR_15_1_i: no maps_to fields extracted

-- SKIPPED ICDR_15_1_ii: no maps_to fields extracted

-- SKIPPED ICDR_15_1_iii: no maps_to fields extracted

-- SKIPPED ICDR_15_1_iv: no maps_to fields extracted

-- SKIPPED ICDR_15_1_explanation: no maps_to fields extracted

-- SKIPPED ICDR_15_1_c: no maps_to fields extracted

-- SKIPPED ICDR_15_1_c_proviso: no maps_to fields extracted

/-- specified securities pledged with any creditor. -/
theorem gold_reg_15_1_d : reg_15_1_d sample_compliant_issuer := by
  sorry

-- SKIPPED ICDR_15_1_iv_proviso: no maps_to fields extracted

/-- Specified securities referred to in clauses (a) and (c) of sub-regulation (1) shall be eligible for ... -/
theorem gold_reg_15_2 : reg_15_2 sample_compliant_issuer := by
  sorry

/-! ### Regulation 16 -/

/-- minimum promoters' contribution including contribution made by alternative investment funds or forei... -/
theorem gold_reg_16_1_a : reg_16_1_a sample_compliant_issuer := by
  sorry

/-- in case the majority of the issue proceeds excluding the portion of offer for sale is proposed to be... -/
theorem gold_reg_16_1_proviso : reg_16_1_proviso sample_compliant_issuer := by
  sorry

/-- promoters' holding in excess of minimum promoters' contribution shall be locked-in for a period of s... -/
theorem gold_reg_16_1_b : reg_16_1_b sample_compliant_issuer := by
  sorry

/-- in case the majority of the issue proceeds excluding the portion of offer for sale is proposed to be... -/
theorem gold_reg_16_1_b_proviso : reg_16_1_b_proviso sample_compliant_issuer := by
  sorry

-- SKIPPED ICDR_16_1_explanation: no maps_to fields extracted

/-- The SR equity shares shall be under lock-in until conversion into equity shares having voting rights... -/
theorem gold_reg_16_2 : reg_16_2 sample_compliant_issuer := by
  sorry

/-! ### Regulation 17 -/

/-- The entire pre-issue capital held by persons other than the promoters shall be locked-in for a perio... -/
theorem gold_reg_17 : reg_17 sample_compliant_issuer := by
  sorry

-- SKIPPED ICDR_17_proviso: no maps_to fields extracted

-- SKIPPED ICDR_17_a: no maps_to fields extracted

-- SKIPPED ICDR_17_b: no maps_to fields extracted

-- SKIPPED ICDR_17_b_proviso: no maps_to fields extracted

-- SKIPPED ICDR_17_c: no maps_to fields extracted

/-- such equity shares shall be locked in for a period of at least six months from the date of purchase ... -/
theorem gold_reg_17_c_proviso : reg_17_c_proviso sample_compliant_issuer := by
  sorry

-- SKIPPED ICDR_17_explanation_i: no maps_to fields extracted

-- SKIPPED ICDR_17_explanation_ii: no maps_to fields extracted

-- SKIPPED ICDR_17_explanation_iii: no maps_to fields extracted

/-! ### Regulation 18 -/

-- SKIPPED ICDR_18: no maps_to fields extracted

-- SKIPPED ICDR_18_proviso: no maps_to fields extracted

/-! ### Regulation 19 -/

/-- If the specified securities which are subject to lock-in are partly paid-up and the amount called-up... -/
theorem gold_reg_19 : reg_19 sample_compliant_issuer := by
  sorry

/-! ### Regulation 20 -/

/-- The certificates of specified securities which are subject to lock-in shall contain the inscription ... -/
theorem gold_reg_20 : reg_20 sample_compliant_issuer := by
  sorry

/-! ### Regulation 21 -/

/-- Specified securities, except SR equity shares, held by the promoters and locked-in may be pledged as... -/
theorem gold_reg_21 : reg_21 sample_compliant_issuer := by
  sorry

-- SKIPPED ICDR_21_a: no maps_to fields extracted

-- SKIPPED ICDR_21_b: no maps_to fields extracted

-- SKIPPED ICDR_21_proviso: no maps_to fields extracted

/-! ### Regulation 22 -/

-- SKIPPED ICDR_22: no maps_to fields extracted

-- SKIPPED ICDR_22_proviso: no maps_to fields extracted

/-! ### Regulation 23 -/

/-- The issuer shall appoint one or more merchant bankers, which are registered with the Board, as lead ... -/
theorem gold_reg_23_1 : reg_23_1 sample_compliant_issuer := by
  sorry

-- SKIPPED ICDR_23_2: no maps_to fields extracted

/-- At least one lead manager to the issue shall not be an associate of the issuer and if any of the lea... -/
theorem gold_reg_23_3 : reg_23_3 sample_compliant_issuer := by
  sorry

-- SKIPPED ICDR_23_4: no maps_to fields extracted

/-- The issuer shall enter into an agreement with the lead manager(s) in the format specified in Schedul... -/
theorem gold_reg_23_5 : reg_23_5 sample_compliant_issuer := by
  sorry

-- SKIPPED ICDR_23_5_proviso: no maps_to fields extracted

/-! ## Composite Gate Theorems -/
--
-- These prove reg_N_eligible (the conjunction of all sub-clauses).
-- APOLLO decomposition: prove each sub-clause first, then combine.

/-- Composite gate: reg_5_eligible = reg_5_1_a, reg_5_1_b, reg_5_1_c, reg_5_1_d, reg_5_2 -/
theorem gold_reg_5_eligible : reg_5_eligible sample_compliant_issuer := by
  sorry

/-- Composite gate: reg_6_eligible = reg_6_1_a, reg_6_1_b, reg_6_1_c, reg_6_1_d, reg_6_2, reg_6_3, reg_6_3_i, reg_6_3_ii, reg_6_3_iii, reg_6_3_iv, reg_6_3_iv_a, reg_6_3_iv_b, reg_6_3_iv_c, reg_6_3_iv_d, reg_6_3_iv_e, reg_6_3_v, reg_6_3_vi, reg_6_3_vii, reg_6_3_viii, reg_6_3_ix -/
theorem gold_reg_6_eligible : reg_6_eligible sample_compliant_issuer := by
  sorry

/-- Composite gate: reg_7_eligible = reg_7_1_b, reg_7_1_c, reg_7_1_d, reg_7_1_e, reg_7_2, reg_7_3 -/
theorem gold_reg_7_eligible : reg_7_eligible sample_compliant_issuer := by
  sorry

/-- Composite gate: reg_8_eligible = reg_8, reg_8a_a, reg_8a_b, reg_8a_c -/
theorem gold_reg_8_eligible : reg_8_eligible sample_compliant_issuer := by
  sorry

/-- Composite gate: reg_10_eligible = reg_10_1_a, reg_10_1_b, reg_10_1_d_i, reg_10_1_d_ii, reg_10_1_d_iii, reg_10_2 -/
theorem gold_reg_10_eligible : reg_10_eligible sample_compliant_issuer := by
  sorry

/-- Composite gate: reg_11_eligible = reg_11_1, reg_11_2, reg_11_3 -/
theorem gold_reg_11_eligible : reg_11_eligible sample_compliant_issuer := by
  sorry

/-- Composite gate: reg_13_eligible = reg_13_a, reg_13_c, reg_13_d -/
theorem gold_reg_13_eligible : reg_13_eligible sample_compliant_issuer := by
  sorry

/-- Composite gate: reg_14_eligible = reg_14_1, reg_14_a, reg_14_b, reg_14_c -/
theorem gold_reg_14_eligible : reg_14_eligible sample_compliant_issuer := by
  sorry

/-- Composite gate: reg_15_eligible = reg_15_1_b, reg_15_1_d, reg_15_2 -/
theorem gold_reg_15_eligible : reg_15_eligible sample_compliant_issuer := by
  sorry

/-- Composite gate: reg_16_eligible = reg_16_1_a, reg_16_1_b, reg_16_2 -/
theorem gold_reg_16_eligible : reg_16_eligible sample_compliant_issuer := by
  sorry

/-- Composite gate: reg_23_eligible = reg_23_1, reg_23_3, reg_23_5 -/
theorem gold_reg_23_eligible : reg_23_eligible sample_compliant_issuer := by
  sorry

end Reglib.ICDR.Rules
