-- Reglib.lean
-- Root import -- auto-generated by generate_reglib.py

import Reglib.ICDR.definitions.Core
import Reglib.ICDR.rules.Chapter2_Part1
import Reglib.ICDR.rules.Chapter2_Part2
import Reglib.ICDR.rules.Chapter2_Part3
import Reglib.ICDR.rules.Chapter2_Part4
import Reglib.ICDR.rules.Chapter2_Part5
import Reglib.ICDR.rules.Compliance
