-- Reglib/ICDR/2018/definitions/Core.lean
-- Core regulatory types for SEBI_ICDR_2018
-- Auto-generated by generate_reglib.py
-- Sources: rules JSONL + definitions JSONL (Reg 2 statutory definitions)
-- DO NOT EDIT MANUALLY — re-run the generator after updating either JSONL

namespace Reglib.ICDR

/-! ## Primitive Type Aliases -/

/-- Indian Rupee amount in crore (1 crore = 10 million) -/
abbrev INR_Crore := Nat

/-- Percentage value as integer (0–100) -/
abbrev Pct := Nat

/-- Duration in months -/
abbrev Months := Nat

/-- Duration in years -/
abbrev Years := Nat

/-! ## Inductive Types — grounded in Reg 2 statutory definitions -/

/-- Reg 2(eee), 2(eeea): specified securities -/
inductive SpecifiedSecurities where
  | equityShares          -- Reg 2(eee)
  | convertibleSecurities -- Reg 2(eee)
  | srEquityShares        -- Reg 2(eeea): superior voting rights
deriving Repr, DecidableEq

/-- Combined issue type — Reg 2(w),(q),(h),(xx),(nn),(tt) -/
inductive IssueType where
  | initialPublicOffer  -- Reg 2(w)
  | furtherPublicOffer  -- Reg 2(q)
  | compositeIssue      -- Reg 2(h): public-cum-rights simultaneously
  | rightsIssue         -- Reg 2(xx)
  | preferentialIssue   -- Reg 2(nn)
  | qualifiedPlacement  -- Reg 2(tt)
deriving Repr, DecidableEq

/-- Reg 2(k): convertible security -/
inductive ConvertibleSecurity where
  | convertibleIntoEquityShares
  | convertibleDebtInstrument
  | convertiblePreferenceShares
deriving Repr, DecidableEq

/-- Reg 2(ss): qualified institutional buyer -/
inductive QualifiedInstitutionalBuyer where
  | mutualFund
  | ventureCapitalFund
  | alternativeInvestmentFund
  | foreignVentureCapitalInvestor
  | publicFinancialInstitution
  | scheduledCommercialBank
  | multilateralAndBilateralDevelopmentFinancialInstitution
  | stateIndustrialDevelopmentCorporation
  | insuranceCompany
  | providentFund
  | pensionFund
  | nationalInvestmentFund
  | militaryInsuranceFunds
  | departmentOfPostsInsuranceFunds
deriving Repr, DecidableEq

/-- Reg 2(v): infrastructure sector -/
inductive InfrastructureSector where
  | transportation
  | agriculture
deriving Repr, DecidableEq

/-! ## Promoter — Reg 2(oo) -/

/-- A person included as promoter under any limb of Reg 2(oo)(i–iii) -/
structure Promoter where
  /-- Reg 2(oo)(i): named in offer doc or annual return (s.92 Companies Act) -/
  named_in_offer_doc                : Bool
  /-- Reg 2(oo)(ii): control as shareholder/director/otherwise -/
  has_control                       : Bool
  /-- Reg 2(oo)(iii): board accustomed to act on their advice -/
  board_acts_on_instructions        : Bool
  /-- Reg 2(oo) proviso: professional capacity only → excluded from promoter status -/
  acting_only_professionally        : Bool
  holding_pct                       : Pct
  is_debarred                       : Bool
  /-- Reg 2(lll) -/
  is_wilful_defaulter_or_fraudulent : Bool
  /-- Reg 2(p) -/
  is_fugitive_economic_offender     : Bool
deriving Repr

/-! ## Issuer — Reg 2(aa) -/

/-- "a company or a body corporate authorized to issue specified securities" -/
structure Issuer where
  /-- Reg 10(1)(d)(i) (maps_to inference) -/
  assets_cover_principal_amount                    : Bool
  /-- Reg 10(1)(d)(ii) (maps_to inference) -/
  assets_free_from_encumbrance                     : Bool
  /-- Reg 11(2) (maps_to inference) -/
  convertible_debt_instruments_value_exceeds       : INR_Crore
  /-- Reg 7(1)(e) (maps_to inference) -/
  finance_arrangements_pct                         : Nat
  /-- Reg 13(c)(proviso) (maps_to inference) -/
  formula_based_warrants_upfront_contribution_pct  : Nat
  /-- Reg 12(proviso) (maps_to inference) -/
  fully_convertible_debt_period_months             : Months
  /-- Reg 7(2) (maps_to inference) -/
  general_corporate_purpose_pct_limit              : Nat
  /-- Reg 10(1)(b) (maps_to inference) -/
  has_appointed_debenture_trustee                  : Bool
  /-- Reg 10(1)(a) (maps_to inference) -/
  has_credit_rating_from_one_agency                : Bool
  /-- Reg 5(1)(b) (maps_to inference) -/
  has_debarred_promoter_or_director                : Bool
  /-- Reg 7(1)(b) (maps_to inference) -/
  has_depository_agreement                         : Bool
  /-- Reg 23(3) (maps_to inference) -/
  has_non_associate_lead_manager                   : Bool
  /-- Reg 11(1) (maps_to inference) -/
  has_positive_consent_from_holders                : Bool
  /-- Reg 10(1)(d)(iii) (maps_to inference) -/
  has_second_or_pari_passu_charge_consent          : Bool
  /-- Reg 17(explanation)(i) (maps_to inference) -/
  holding_period_months                            : Months
  /-- Reg 15(1)(b) (maps_to inference) -/
  holding_period_years                             : Years
  /-- Reg 6(2) (maps_to inference) -/
  ipo_book_building_pct                            : Nat
  /-- Reg 5(explanation) (maps_to inference) -/
  is_debarment_period_over                         : Bool
  /-- Reg 5(1)(a) (maps_to inference) -/
  is_debarred                                      : Bool
  /-- Reg 12 (maps_to inference) -/
  is_eligible_for_convertible_debt_instruments     : Bool
  /-- Reg 5(1)(d) (maps_to inference) -/
  is_fugitive_economic_offender                    : Bool
  /-- Reg 20 (maps_to inference) -/
  is_lock_in_recorded_by_depository                : Bool
  /-- Reg 8a(c) (maps_to inference) -/
  is_over_20_pct_pre_issue_shareholder             : Bool
  /-- Reg 7(1)(d) (maps_to inference) -/
  is_partly_paidup_shares_forfeited_or_fully_paid_up : Bool
  /-- Reg 11(3) (maps_to inference) -/
  is_redeemed_within_month                         : Bool
  /-- Reg 6(3)(iii) (maps_to inference) -/
  is_sr_shares_issued_to_executive_promoters_only  : Bool
  /-- Reg 5(1)(c) (maps_to inference) -/
  is_wilful_defaulter_or_fraudulent_borrower       : Bool
  /-- Reg 15(1)(a)(c) (maps_to inference) -/
  issuer_conversion_from_partnership_or_llp        : Bool
  /-- Reg 6(1)(a) (maps_to inference) -/
  monetary_assets_pct_limit                        : Nat
  /-- Reg 6(1)(a) (maps_to inference) -/
  net_tangible_assets_3yr                          : List INR_Crore
  /-- Reg 6(1)(c) (maps_to inference) -/
  net_worth_3yr                                    : List INR_Crore
  /-- Reg 9(proviso) (maps_to inference) -/
  no_default_payment_more_than_six_months          : Bool
  /-- Reg 17 (maps_to inference) -/
  non_promoter_lock_in_period_months               : Months
  /-- Reg 16(1)(b) (maps_to inference) -/
  ofs_holding_period_months_reg16                  : Months
  /-- Reg 17(1)(b)(proviso) (maps_to inference) -/
  ofs_holding_period_months_reg17                  : Months
  /-- Reg 19 (maps_to inference) -/
  ofs_holding_period_years                         : Years
  /-- Reg 16(1)(a)(proviso) (maps_to inference) -/
  ofs_lock_in_period_years                         : Years
  /-- Reg 6(1)(b) (maps_to inference) -/
  operating_profit_last_3yr                        : List INR_Crore
  /-- Reg 14(3) (maps_to inference) -/
  promoter_compliance_deadline_days_prior_issue_opening : Nat
  /-- Reg 16(1)(a) (maps_to inference) -/
  promoter_contribution_lock_in_months             : Months
  /-- Reg 13(c)(a) (maps_to inference) -/
  promoter_contribution_pct                        : Nat
  /-- Reg 14(c) (maps_to inference) -/
  promoter_contribution_pct_project_cost           : Nat
  /-- Reg 14(b) (maps_to inference) -/
  promoter_contribution_price_lower_limit          : Nat
  /-- Reg 16(1) (maps_to inference) -/
  promoter_lock_in_period_months                   : Months
  /-- Reg 14(a) (maps_to inference) -/
  promoter_min_contribution_pct                    : Nat
  /-- Reg 14(1) (maps_to inference) -/
  promoter_min_post_issue_capital_pct              : Nat
  /-- Reg 15(1)(a)(iv)(proviso) (maps_to inference) -/
  promoter_securities_eligibility_period_months    : Months
  /-- Reg 7(1)(c) (maps_to inference) -/
  promoter_shares_dematerialised                   : Bool
  /-- Reg 14(4) (maps_to inference) -/
  promoters_contribution_escrow_account            : Bool
  /-- Reg 15(1)(a)(c) (maps_to inference) -/
  promoters_of_converted_entity                    : List INR_Crore
  /-- Reg 6(1)(d) (maps_to inference) -/
  revenue_from_new_activity_pct                    : Nat
  /-- Reg 8a(a) (maps_to inference) -/
  shareholder_offer_limit_pct                      : Nat
  /-- Reg 8a(b) (maps_to inference) -/
  small_shareholder_offer_limit_pct                : Nat
  /-- Reg 6(v) (maps_to inference) -/
  sr_equity_share_holding_period_months            : Months
  /-- Reg 6(3)(ii) (maps_to inference) -/
  sr_shareholder_net_worth_max_crore               : Nat
  /-- Reg 7(3)(proviso) (maps_to inference) -/
  unspecified_objects_pct_limit                    : Nat
  /-- Reg 7(3) (maps_to inference) -/
  untargeted_acquisition_investment_pct_limit      : Nat
  /-- Reg 13 (maps_to inference) -/
  warrant_consideration_upfront_pct                : Nat
  /-- Reg 13(d) (maps_to inference) -/
  warrant_exercise_period_months                   : Months
  /-- Reg 13(a) (maps_to inference) -/
  warrant_tenure_months                            : Months
  /-- What kind of issue this filing is for -/
  issue_type                                         : IssueType
  /-- Type of securities being issued — Reg 2(eee) -/
  specified_securities_type                          : SpecifiedSecurities
  /-- Reg 2(oo) -/
  promoters                                          : List Promoter
deriving Repr

end Reglib.ICDR